### ISSUE TITLE
Language is set to French

### ISSUE THREAD

**Issue by theSdev** [anthonydahanne/newsy-mastodon#1]
Hello and thank you for the bot.
I've realized that the posts are marked as being in French, and although it doesn't affect me personally, I think it wouldn't harm to fix the language to be English.

**Comment by anthonydahanne** [comment]
Hello!
thanks for your issue!

how can I change the posts languages? is it in the API?

probably they're marked as french by default because framapiaf is a french mastodon instance.

**Comment by theSdev** [comment]
I don't know the API really, but there's a setting for it in the web interface. Here's what I [found](https://fedi.tips/setting-your-language-preferences-on-mastodon-and-filtering-out-posts-in-other-languages/):

> To set which language you post in:
    Log in through your server’s website
    Go to Preferences > Other > Posting language
    Choose which language you use most often and click Save changes

**Comment by anthonydahanne** [comment]
hey there @theSdev .
Yeah there's the feature in the API to set the language per toot; apparently it's a big deal since some users use language based filters.
It should be fixed now: here's a toot [before](https://framapiaf.org/api/v1/statuses/112180870320094571) (notice `language: fr`) ; and here's a toot [after deployment](https://framapiaf.org/api/v1/statuses/112181342783491010) of the latest version (notice `language: en`)

Let me know if it's not fixed to you! Thanks!
